### ISSUE TITLE
pandas.core.indexing.IndexingError: Too many indexers

### ISSUE THREAD

**Issue by rvolden** [asrhou/scMatch#1]
When I try to run scMatch.py, using this command:
```bash
python2 scMatch.py --refDS refDB/FANTOM5/ --dFormat csv --testDS ill_4rep2_gene_exp.csv --testMethod both --keepZeros n --coreNum 30
```

<details><summary>I get this pandas error:</summary>
<p>

```
Traceback (most recent call last):
  File "scMatch.py", line 353, in <module>
    main(testType, opt.dFormat, opt.testDS, opt.testGenes, opt.refDS, refTypeList, keepZeros, testMethodList, opt.coreNum)
  File "scMatch.py", line 194, in main
    AnnSCData(testType, em, refDS, refType, hidSpecDict[refType], keepZeros, testMethod, coreNum, savefolder)
  File "scMatch.py", line 102, in AnnSCData
    resultList = p.map(func, eps)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
pandas.core.indexing.IndexingError: Too many indexers
```

</p>
</details>

I'm not sure if this is specific to your program and how it's indexing using pandas. To make sure it isn't something specific to my input, I tried with the example file:

```bash
python2 scMatch.py --refDS refDB/FANTOM5/ --dFormat csv --testDS GSE81861_Cell_Line_COUNT.csv --testMethod both --keepZeros n --coreNum 30
```

which returns the same error. 

The only thing I did was unzip the *.zip files in `refDB/FANTOM5/` and then try to run the command. I've also tried this on another computer, which produced the same error.

<details><summary>pd.show_versions() output:</summary>
<p>

```
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.12.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.0-145-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: None.None

pandas: 0.24.2
pytest: None
pip: 19.1
setuptools: 20.7.0
Cython: 0.29.7
numpy: 1.16.3
scipy: 1.2.1
pyarrow: None
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.8.0
pytz: 2019.1
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.2.4
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml.etree: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None
```

</p>
</details>

From digging around, similar issues seem to be associated with a different pandas function as opposed to the map function that you're calling.

It would be great if you could help me out here since I'm not overly familiar with pandas. Thanks!

**Comment by asrhou** [comment]
Dear Roger,
   
Sorry for the late response. map function hides the real issue in the SPMAnno function. It seems there are duplicated gene names in 'ill_4rep2_gene_exp.csv'. When I used your command to annotate 'GSE81861_Cell_Line_COUNT.csv', I can't repeat your error. You can send me those two CSV files [rui.hou@research.uwa.edu.au] and I will check them for you. 

Best,
Rui

**Comment by rvolden** [comment]
I actually found a workaround to analyze my data with another package, but thank you!

**Comment by kvshams** [comment]
Any fix to this issue? I am also getting the same error @rvolden any suggestions?

**Comment by rvolden** [comment]
I stopped trying to figure this out once I found another way to analyze my data (I used Seurat and looked at gene expression myself). Sorry about that

**Comment by kvshams** [comment]
it is present only when `--refType both`

**Comment by rvolden** [comment]
I didn't specify refType since it defaults to human, and my dataset was only human
Do you mean `--testMethod`?

**Comment by kvshams** [comment]
Thanks @rvolden. I did not use `--testMethod`. More over, seems to be there is a bias towards  immune cells. This works very well with immune cells but really gives misclassification couple of other tissues tried!
