### ISSUE TITLE
pandas .ix depreciation

### ISSUE THREAD

**Issue by HypoChloremic** [asrhou/scMatch#10]
# Pandas .ix depreciated
Fresh installs of pandas does note work with scmatch. 
Line 93 of scMatch.py in `AnnSCData` uses: 
`refDB = refDB.ix[~refDB.index.duplicated(keep='first'),]`
which calls a now depreciated a method of pandas DataFrame.

**Comment by asrhou** [comment]
Thank you for the information! I think in this line, you can replace it with 

`refDB = refDB.loc[~refDB.index.duplicated(keep='first'),]`
