### ISSUE TITLE
Naming inconsistency

### ISSUE THREAD

**Issue by kerimsecener** [asrhou/scMatch#7]
Hello,

I think you need to change "genes.tsv" into "features.tsv" in the script VisAnnos.py in this line:
row = pd.read_table(fileItem[:-10]+"genes.tsv", header=None, index_col=None) 

Thanks

**Comment by ishaan-mehta** [comment]
This is also found in lines 153 and 154 for the error message

**Comment by asrhou** [comment]
Thank you, guys! This issue has been fixed.
